name: TEST RELEASE

on:
  release:
    types: [published]

jobs:
  myrelease:
    if: sh test.sh
    name: test release
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'TEST RELEASE'
