name: TEST RELEASE

on:
  release:
    types: [published]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  myrelease:
    name: test release
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo 'TEST RELEASE'
